# fly.toml app configuration file generated for elpactoclub on 2026-05-22T15:06:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'elpactoclub'
primary_region = 'cdg'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '4000'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
